export const ERROR_CODES = {
  AUTH_UNAUTHORIZED: "AUTH_UNAUTHORIZED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  LLM_JSON_INVALID: "LLM_JSON_INVALID",
  UPSTREAM_TIMEOUT: "UPSTREAM_TIMEOUT",
  DB_ERROR: "DB_ERROR",
  UNKNOWN: "UNKNOWN",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
